controllers/ClubController.php
<?php

namespace app\controllers;

use app\models\CategorySport;
use app\models\KindSport;
use app\models\Club;

class ClubController extends \yii\web\Controller
{
    public function actionIndex()
    {
        $categories = CategorySport::getCategories();
        return $this->render('index', [
            'categories' => $categories,
        ]);
    }

    public function actionKindSport($id) {
        $category_id = $id;
        $kinds_sport = KindSport::getKindsSport($category_id);
        $category_sport = CategorySport::getCategory($category_id);

        return $this->render('kinds_sports', [
            'kinds_sport' => $kinds_sport,
            'category_sport' => $category_sport,
        ]);
    }

    public function actionClubsList($id) {
        $kind_club_id = $id;
        $clubs_list = Club::getClubs($kind_club_id);
        $kind_sport = KindSport::getNameKind($kind_club_id);

        return $this->render('clubs_list', [
            'clubs_list' => $clubs_list,
            'kind_sport' => $kind_sport,
        ]);
    }

    public function actionClub($id)
    {
        $club = Club::getClub($id);
        //var_dump($club);
        return $this->render('club',[
            'club' => $club,
        ]);
    }

}

controllers/SecurityController.php
<?php

namespace app\controllers;

use Yii;
use app\models\User;
use app\models\LoginForm;
use app\config\Constants;
use app\models\RegistrationToUser;
use app\models\RegistrationToClub;

class SecurityController extends \yii\web\Controller
{
    public $username;
    public $email;

    /**
     * Login action.
     *
     * @return string
     */

    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return string
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    public function actionRegistration()
    {
        return $this->render('registration');
    }

    public function actionUser()
    {
        $model = new RegistrationToUser();

        if($model->load(Yii::$app->request->post()) && $model->validate())
        {
            if($user = $model->registration())
            {
                if (Yii::$app->getUser()->login($user))
                {
                    if($user->status === Constants::STATUS_ACTIVE)
                    {
                        return $this->goHome();
                    }
                }

            }
        }

        return $this->render('user', ['model' => $model]);
    }

    public function actionClub()
    {
        $model = new RegistrationToClub();

        if($model->load(Yii::$app->request->post()) && $model->validate())
        {

            if($user = $model->registration())
            {
                if (Yii::$app->getUser()->login($user))
                {
                    if($user->status === Constants::STATUS_ACTIVE)
                    {
                        return $this->goHome();
                    }
                }

            }
        }

        return $this->render('club', ['model' => $model]);
    }

}

views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;
use app\config\Constants;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
    <?php $this->registerCssFile($this->registerCssFile('@web/css/main.css')) ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrapper">

    <header>
        <div class="lincs">
            <div class="link-to-home"><?= Html::a('Додому', ['/']) ?></div>

            <div class="link-header">
                <?= Html::a('Новини', ['/news/index']) ?> &nbsp; | &nbsp;
                <?= Html::a('Івенти', ['/event/index']) ?> &nbsp; | &nbsp;
                <?= Html::a('Спортивні клуби', ['/club/index']) ?> &nbsp; | &nbsp;

                <?php if(Yii::$app->user->isGuest): ?>
                    <?= Html::a('Зареєструватись', ['/security/registration']) ?> &nbsp; | &nbsp;
                    <?= Html::a('Увійти', ['/security/login']) ?>
                <?php endif; ?>

                <?php if(!Yii::$app->user->isGuest && Yii::$app->user->identity->user_group == Constants::USER_GROUP): ?>
                    <?= Html::a('Кабінет', ['/user-cabinet']) ?> &nbsp; | &nbsp;
                    <?= Html::a('Вийти', ['/security/logout']) ?> (<?= Yii::$app->user->identity->username; ?>)
                <?php endif; ?>

                <?php if(!Yii::$app->user->isGuest && Yii::$app->user->identity->user_group == Constants::OWNER_GROUP): ?>
                    <?= Html::a('Кабінет', ['/owner-cabinet']) ?> &nbsp; | &nbsp;
                    <?= Html::a('Вийти', ['/security/logout']) ?> (<?= Yii::$app->user->identity->username; ?>)
                <?php endif; ?>
            </div>
        </div>
    </header>

    <div class="main-container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= $content ?>
    </div>


<footer class="footer">
    <div class="container">
        <p class="pull-left">&copy; My Company <?= date('Y') ?></p>

        <p class="pull-right"><?= Yii::powered() ?></p>
    </div>
</footer>
</div>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

views/layouts/mains.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;
use app\config\Constants;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php
    NavBar::begin([
        'brandLabel' => 'My Company',
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
    ]);
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => [
            ['label' => 'Новини', 'url' => ['/site/index']],
            ['label' => 'Статі', 'url' => ['/site/about']],
            ['label' => 'Спорт Клуби', 'url' => ['/site/contact']],
            Yii::$app->user->identity['user_group'] == Constants::USER_GROUP ? (['label' => 'Кабінет', 'url' => ['/user-cabinet/']]): (''),
            Yii::$app->user->isGuest ? (['label' => 'Реєстрація', 'url' => ['/security/registration']]): (''),
            Yii::$app->user->isGuest ? (
                ['label' => 'Вхід', 'url' => ['/security/login']]
            ) : (
                '<li>'
                . Html::beginForm(['/security/logout'], 'post')
                . Html::submitButton(
                    'Вийти (' . Yii::$app->user->identity->username . ')',
                    ['class' => 'btn btn-link logout']
                )
                . Html::endForm()
                . '</li>'
            )
        ],
    ]);
    NavBar::end();
    ?>

    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= $content ?>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <p class="pull-left">&copy; My Company <?= date('Y') ?></p>

        <p class="pull-right"><?= Yii::powered() ?></p>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>