module/ownerCabinet/models/UserCabinet.php
<?php

namespace app\module\ownerCabinet\models;

use Yii;
use app\module\ownerCabinet\models\UserData;

/**
 * This is the model class for table "users".
 *
 * @property integer $id
 * @property string $username
 * @property string $password
 * @property string $email
 * @property integer $status
 * @property integer $user_group
 * @property string $aut_key
 * @property string $access_token
 * @property string $create_at
 * @property string $update_at
 */
class UserCabinet extends \yii\db\ActiveRecord
{

    public $old_password;
    public $new_password_1;
    public $new_password_2;


    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'users';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [

            [['old_password', 'new_password_1', 'new_password_2'], 'required'],
            [['old_password'], 'checkCorrectOldPassword'],
            [['new_password_1', 'new_password_2'], 'checkCoincidencePassword'],
            ['new_password_1', 'string', 'min' => 4, 'max' => 120 ],
            ['new_password_2', 'string', 'min' => 4, 'max' => 120 ],
            [['status', 'user_group'], 'integer'],
            [['create_at', 'update_at'], 'safe'],
            [['username', 'password', 'email'], 'string', 'max' => 255],
            [['aut_key', 'access_token'], 'string', 'max' => 32],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'username' => 'Username',
            'password' => 'Password',
            'email' => 'Email',
            'status' => 'Status',
            'user_group' => 'User Group',
            'aut_key' => 'Aut Key',
            'access_token' => 'Access Token',
            'create_at' => 'Create At',
            'update_at' => 'Update At',
            'old_password' => 'Ваший поточний пароль',
            'new_password_1' => 'Новий пароль',
            'new_password_2' => 'Новий пароль',
        ];
    }

    public function checkCorrectOldPassword($attribute, $params)
    {
        $password = self::findOne([
            'username' => Yii::$app->user->identity->username,
        ]);

        if(!Yii::$app->getSecurity()->validatePassword($this->old_password, $password->password))
        {
            $this->addError($attribute, 'Пароль не вірний');
        }
    }

    public function checkCoincidencePassword($attribute, $params)
    {

        $password = self::findOne([
            'username' => Yii::$app->user->identity->username,
        ]);

        if(Yii::$app->getSecurity()->validatePassword($this->new_password_1, $password->password) && Yii::$app->getSecurity()->validatePassword($this->new_password_2, $password->password))
        {
            $this->addError($attribute, 'Новий пароль не може співпадати зі старим');
        }

        if($this->new_password_1 != $this->new_password_2)
        {
            $this->addError($attribute, 'Паролі не співпадають');
        }


    }

    public function getUserData()
    {
        return $this->hasOne(UserData::className(), ['user_id' => 'id']);
    }

    public function getOwnerClub()
    {
        return $this->hasOne(UserClub::className(), ['user_id' => 'id']);
    }

    public static function getUser($id)
    {
        return self::findOne([
            'id' => $id,
            'username' => Yii::$app->user->identity->username,
            'email' => Yii::$app->user->identity->email,
        ]);
    }
}

module/ownerCabinet/controllers/DefaultController.php
<?php

namespace app\module\ownerCabinet\controllers;

use Yii;
use app\module\ownerCabinet\Access;
use app\module\ownerCabinet\models\UserCabinet;


/**
 * Default controller for the `ownerCabinet` module
 */
class DefaultController extends Access
{
    /**
     * Renders the index view for the module
     * @return string
     */
    public function actionIndex()
    {
        $user_data = UserCabinet::getUser(Yii::$app->user->identity->id);

        return $this->render('index', [
            'user_data' => $user_data,
        ]);
    }
}

module/ownerCabinet/views/default/index.php
<?php


use yii\helpers\Html;
use app\config\Constants;
use mylibrarys\CheckImage;
use mylibrarys\ModalWindow;

$this->title = 'Кабінет';
$this->params['breadcrumbs'][] = $this->title;

?>

<div class="ownerCabinet-default-index">
    <div class="profile">
        <div class="image_profile">
            <img src="<?= CheckImage::checkFileAvatar(Constants::PATH_USER_AVATAR_VIEW, $user_data->userData->photo, Constants::NOT_IMAGE_AVATAR) ?>" >
        </div>
        <div class="user_name">
            Користувач: <br>
            <span><?= $user_data->username; ?></span>
        </div>

        <div class="user_data">
            <hr>
            <strong>Про Користувача:</strong>
            <p>
                Зареєстрований: <?= substr($user_data->userData->create_at, 0, 10); ?>
            </p>

            <hr>
            <strong>Керування профілем:</strong>
            <p>
                <?= Html::a('Змінити аватар', ['/owner-cabinet/control/photo']) ?> <br>
                <?= Html::a('Змінити пароль', ['/owner-cabinet/control/password']) ?>


            </p>

        <hr>
            <strong>Керування клубами:</strong>
            <p>
                <?= Html::a('Керування клубами', ['/owner-cabinet/control-club']) ?> <br>
                <?= Html::a('Змінити пароль', ['/owner-cabinet/control/password']) ?>


            </p>
        </div>
        </div>


    </div>
</div>