controllers/SecurityController.php
<?php

namespace app\controllers;

use Yii;
use app\models\User;
use app\models\LoginForm;
use app\config\Constants;
use app\models\RegistrationToUser;
use app\models\RegistrationToClub;

class SecurityController extends \yii\web\Controller
{
    public $username;
    public $email;

    /**
     * Login action.
     *
     * @return string
     */

    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return string
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    public function actionRegistration()
    {
        return $this->render('registration');
    }

    public function actionUser()
    {
        $model = new RegistrationToUser();

        if($model->load(Yii::$app->request->post()) && $model->validate())
        {
            if($user = $model->registration())
            {
                if (Yii::$app->getUser()->login($user))
                {
                    if($user->status === Constants::STATUS_ACTIVE)
                    {
                        return $this->goHome();
                    }
                }

            }
        }

        return $this->render('user', ['model' => $model]);
    }

    public function actionClub()
    {
        $model = new RegistrationToClub();

        if($model->load(Yii::$app->request->post()) && $model->validate())
        {

            if($user = $model->registration())
            {
                if (Yii::$app->getUser()->login($user))
                {
                    if($user->status === Constants::STATUS_ACTIVE)
                    {
                        return $this->goHome();
                    }
                }

            }
        }

        return $this->render('club', ['model' => $model]);
    }

}

views/security/club.php
<?php
/**
/* @var $this yii\web\View */
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
?>

<div class="main-reg">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'clubName') ?>
    <?= $form->field($model, 'username') ?>
    <?= $form->field($model, 'email') ?>
    <?= $form->field($model, 'password')->passwordInput() ?>
    <?= $form->field($model, 'repeatPassword')->passwordInput() ?>

    <div class="form-group">
        <?= Html::submitButton('Регистрация', ['class' => 'btn btn-primary']) ?>
    </div>
    <?php ActiveForm::end(); ?>

</div><!-- main-reg -->

views/security/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Login';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out the following fields to login:</p>

    <?php $form = ActiveForm::begin([
        'id' => 'login-form',
        'layout' => 'horizontal',
        'fieldConfig' => [
            'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
            'labelOptions' => ['class' => 'col-lg-1 control-label'],
        ],
    ]); ?>

        <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

        <?= $form->field($model, 'password')->passwordInput() ?>

        <?= $form->field($model, 'rememberMe')->checkbox([
            'template' => "<div class=\"col-lg-offset-1 col-lg-3\">{input} {label}</div>\n<div class=\"col-lg-8\">{error}</div>",
        ]) ?>

        <div class="form-group">
            <div class="col-lg-offset-1 col-lg-11">
                <?= Html::submitButton('Війти', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
                <?= Html::a('Зареєструватись', ['security/registration'], ['class'=>'btn btn-primary']) ?>
            </div>
        </div>

    <?php ActiveForm::end(); ?>


</div>

views/security/registration.php
<?php
/* @var $this yii\web\View */
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
?>
<h1>Як ви хочете зарееструватись:</h1>

<p>

    <?= Html::a('Користувач', ['/security/user'], ['class'=>'btn btn-primary']) ?>
    <?= Html::a('Аміністратор клубу', ['/security/club'], ['class'=>'btn btn-primary']) ?>
</p>

<div class="col-lg-offset-1" style="color:#999;">
    <p>Ви можете зареєструватись як звичайний користувач натиснувши кнопку <strong>'Користувач'</strong>
    <br/> у вас буде доступ до вашого кабінету але ви не зможете додавати <strong>Клуби</strong>(спортзали та інше).
    <br/> Ви зможете додавати кометарі до клубів та подій, підпісуватись на них.</p>
    <p>Aбо як власник(адміністратор) клубу натиснувши кнопку <strong>'Адміністратор клубу'</strong>.
    <br> у вас буде доступ до вашого кабінету але ви зможете додавати <strong>Клуби</strong>(спортзали та інше).
    <br> Ви зможете додавати кометарі до клубів та подій, підпісуватись на них.</p>
</div>

views/security/user.php
<?php
/**
/* @var $this yii\web\View */
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
?>

<div class="main-reg">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'username') ?>
    <?= $form->field($model, 'email') ?>
    <?= $form->field($model, 'password')->passwordInput() ?>
    <?= $form->field($model, 'repeatPassword')->passwordInput() ?>

    <div class="form-group">
        <?= Html::submitButton('Регистрация', ['class' => 'btn btn-primary']) ?>
    </div>
    <?php ActiveForm::end(); ?>

</div><!-- main-reg -->