models/Club.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "clubs".
 *
 * @property integer $id
 * @property integer $club_owner_id
 * @property integer $kind_club_id
 * @property string $name
 * @property string $description
 * @property string $contacts
 * @property string $building_number
 * @property integer $street_id
 * @property integer $city_id
 * @property integer $district_city_id
 * @property integer $area_id
 * @property integer $region_id
 * @property string $coordinates
 * @property string $photos
 * @property integer $status
 * @property string $create_at
 * @property string $update_at
 */
class Club extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'clubs';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['club_owner_id', 'kind_club_id', 'contacts', 'building_number', 'street_id', 'city_id', 'district_city_id', 'area_id', 'region_id', 'coordinates', 'status'], 'required'],
            [['club_owner_id', 'kind_club_id', 'street_id', 'city_id', 'district_city_id', 'area_id', 'region_id', 'status'], 'integer'],
            [['description', 'contacts', 'photos'], 'string'],
            [['create_at', 'update_at'], 'safe'],
            [['name'], 'string', 'max' => 60],
            [['building_number'], 'string', 'max' => 15],
            [['coordinates'], 'string', 'max' => 255],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'club_owner_id' => 'Club Owner ID',
            'kind_club_id' => 'Kind Club ID',
            'name' => 'Name',
            'description' => 'Description',
            'contacts' => 'Contacts',
            'building_number' => 'Building Number',
            'street_id' => 'Street ID',
            'city_id' => 'City ID',
            'district_city_id' => 'District City ID',
            'area_id' => 'Area ID',
            'region_id' => 'Region ID',
            'coordinates' => 'Coordinates',
            'photos' => 'Photos',
            'status' => 'Status',
            'create_at' => 'Create At',
            'update_at' => 'Update At',
        ];
    }

    public static function getClubs($kind_club_id)
    {
        return self::find()
            ->asArray()
            ->where(['kind_club_id' => $kind_club_id])
            ->all();
    }

    public static function getClub($id)
    {
        return self::find()
            ->where(['id' => $id])
            ->one();
    }
}

controllers/ClubController.php
<?php

namespace app\controllers;

use app\models\CategorySport;
use app\models\KindSport;
use app\models\Club;

class ClubController extends \yii\web\Controller
{
    public function actionIndex()
    {
        $categories = CategorySport::getCategories();
        return $this->render('index', [
            'categories' => $categories,
        ]);
    }

    public function actionKindSport($id) {
        $category_id = $id;
        $kinds_sport = KindSport::getKindsSport($category_id);
        $category_sport = CategorySport::getCategory($category_id);

        return $this->render('kinds_sports', [
            'kinds_sport' => $kinds_sport,
            'category_sport' => $category_sport,
        ]);
    }

    public function actionClubsList($id) {
        $kind_club_id = $id;
        $clubs_list = Club::getClubs($kind_club_id);
        $kind_sport = KindSport::getNameKind($kind_club_id);

        return $this->render('clubs_list', [
            'clubs_list' => $clubs_list,
            'kind_sport' => $kind_sport,
        ]);
    }

    public function actionClub($id)
    {
        $club = Club::getClub($id);
        //var_dump($club);
        return $this->render('club',[
            'club' => $club,
        ]);
    }

}

views/club/club.php
<?php
use yii\helpers\Url;
use app\config\Constants;


$names_photo = unserialize($club['photos']);
$name_first_photo = array_shift($names_photo);
$path_photo = Url::to('@web/'.Constants::PATH_CLUBS_IMAGES.$name_first_photo);
?>

<div class="club">

    <div class="club-name"><h2><?= $club['name']?></h2></div>
    <div class="club-photo-div">
        <img class="club-photo" src="<?= $path_photo ?>">
        <?php for($i = 0; $i < count($names_photo); $i++): ?>
            <div class="club-photo-small-div">
                <img class="club-photo-small" src="<?= Url::to('@web/'.Constants::PATH_CLUBS_IMAGES.$names_photo[$i]); ?>">
            </div>
        <?php endfor; ?>
    </div>
    <div class="club-description"><?= $club['description'] ?></div>

</div>

views/club/clubs_list.php
<?php
use yii\helpers\Url;
use app\config\Constants;
/**
 * Created by PhpStorm.
 * User: Sky
 * Date: 02.01.17
 * Time: 15:14
 */

$this->title = $kind_sport['name'];
$this->params['breadcrumbs'][] = ['label' => 'Спортивні клуби', 'url' => ['club/index']];
$this->params['breadcrumbs'][] = ['label' => $kind_sport->category['name'], 'url' => ['club/kind-sport', 'id' => $kind_sport->category['id']]];
$this->params['breadcrumbs'][] = $kind_sport['name'];
?>

<?php if($clubs_list): ?>
    <?php foreach($clubs_list as $key): ?>
        <?php
            $names_photo = unserialize($key['photos']);
            $name_first_photo = array_shift($names_photo);
            $path_photo = Url::to('@web/'.Constants::PATH_CLUBS_IMAGES.$name_first_photo);
        ?>
        <div class="club-list">
            <a href="<?= Yii::$app->urlManager->createUrl(['club/club', 'id' => $key['id']]) ?>"><div><img class="photo" src="<?= $path_photo ?>"></div></a>
            <a href="<?= Yii::$app->urlManager->createUrl(['club/club', 'id' => $key['id']]) ?>"><div class="name"><h2><?= $key['name'] ?></h2></div></a>
            <div class="description"><?= $key['description'] ?></div>
            <div class="contacts">
                <h3>Контакти</h3>
                <pre><?= $key['contacts'] ?></pre>
            </div>
        </div>
    <?php endforeach; ?>

<?php endif; ?>

views/club/index.php
<?php
use yii\helpers\Url;
use yii\helpers\Html;
/* @var $this yii\web\View */
$this->title = 'Cпортивні клуби';
$this->params['breadcrumbs'][] = 'Cпортивні клуби';
?>

<?php foreach($categories as $key): ?>
    <p><?= Html::a($key['name'], ['club/kind-sport', 'id' => $key['id']], ['class' => 'profile-link']) ?></p>
<?php endforeach; ?>

views/club/kinds_sports.php
<?php
use yii\helpers\Url;
use yii\helpers\Html;
/* @var $this yii\web\View */

$this->title = $category_sport['name'];
$this->params['breadcrumbs'][] = ['label' => 'Спортивні клуби', 'url' => ['club/index']];
$this->params['breadcrumbs'][] = $category_sport['name'];
?>

<?php if($kinds_sport): ?>
    <?php foreach($kinds_sport as $key): ?>
        <p><?= Html::a($key['name'], ['club/clubs-list', 'id' => $key['id']], ['class' => 'profile-link']) ?></p>
    <?php endforeach; ?>
<?php else: ?>
   <h3> В даній категорії поки нема клубів </h3>
<?php endif; ?>